version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - $pwd/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
